### ISSUE TITLE
can ask if this is used for the international version of Interpark or the Korean version

### ISSUE THREAD

**Issue by svtjoshuji** [rezeq1978/Interparking#1]
can ask if this is used for the international version of Interpark or the Korean version

**Comment by rezeq1978** [comment]
No this is something different.

**Comment by svtjoshuji** [comment]
Maybe I didn't express it well. What I mean is whether this program is used in the international version or the Korean version. Because the two versions are very different, I have found other programs that have failed because selenium cannot be used in interpark. So I want to find a new program to use, and it is too expensive to buy those who are dedicated to grab tickets, so I want to use the program that has been debugged.
